name: JasonGiordano
favicon: null
layout_spectrum: 1
typography_spectrum: 0.26987602678127587
title: Wedding Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebeffc'
    - '#000000'
    - '#d7a58b'
    - '#4f5b61'
    - '#8e0926'
  brandStrength: 0
  lightness: 0.43398263095878065
  saturation: 0.3168550741393119
  rhythmicContrast: 0.16039550816640258
purpose: []
