name: JasonGiordano
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Wedding Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c5c5c5'
    - '#8d8d8d'
    - '#060606'
    - '#434343'
  brandStrength: 1
  lightness: 0.43398263095878065
  saturation: 0.3168550741393119
  rhythmicContrast: 0.16039550816640258
purpose: []
