name: JasonGiordano
favicon: null
layout_spectrum: 0.07967903814278543
typography_spectrum: 0.26987602678127587
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8417648919858038
  lightness: 0.43398263095878065
  saturation: 0.3168550741393119
  rhythmicContrast: 0.16039550816640258
purpose: []
