name: JasonGiordano
favicon: null
layout_spectrum: 1
typography_spectrum: 0.26987602678127587
title: Wedding Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7ebec'
    - '#b2bdc1'
    - '#131929'
    - '#73736b'
    - '#324200'
  brandStrength: 0
  lightness: 0.43398263095878065
  saturation: 0.3168550741393119
  rhythmicContrast: 0.16039550816640258
purpose: []
